//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datasource
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbs_contactpropertyset
    {
        public long Id { get; set; }
        public int Property { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public byte[] Binary { get; set; }
        public long MBS_ContactId { get; set; }
    
        public virtual mbs_contactset mbs_contactset { get; set; }
    }
}
