//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mobilespyModel", "FK_MBS_SessionMBS_Call", "mbs_sessionset", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mysql_connection_test.mbs_sessionset), "mbs_callset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mysql_connection_test.mbs_callset), true)]
[assembly: EdmRelationshipAttribute("mobilespyModel", "FK_MBS_ContactMBS_ContactProperty", "mbs_contactset", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mysql_connection_test.mbs_contactset), "mbs_contactpropertyset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mysql_connection_test.mbs_contactpropertyset), true)]
[assembly: EdmRelationshipAttribute("mobilespyModel", "FK_MBS_SessionMBS_Contact", "mbs_sessionset", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mysql_connection_test.mbs_sessionset), "mbs_contactset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mysql_connection_test.mbs_contactset), true)]
[assembly: EdmRelationshipAttribute("mobilespyModel", "FK_MBS_DeviceMBS_Session", "mbs_deviceset", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mysql_connection_test.mbs_deviceset), "mbs_sessionset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mysql_connection_test.mbs_sessionset), true)]
[assembly: EdmRelationshipAttribute("mobilespyModel", "FK_MBS_SessionMBS_FileSystem", "mbs_sessionset", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mysql_connection_test.mbs_sessionset), "mbs_filesystemset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mysql_connection_test.mbs_filesystemset), true)]
[assembly: EdmRelationshipAttribute("mobilespyModel", "FK_MBS_SessionMBS_Session", "mbs_sessionset", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(mysql_connection_test.mbs_sessionset), "mbs_sessionset1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mysql_connection_test.mbs_sessionset), true)]
[assembly: EdmRelationshipAttribute("mobilespyModel", "FK_MBS_SessionMBS_SMS", "mbs_sessionset", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mysql_connection_test.mbs_sessionset), "mbs_smsset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mysql_connection_test.mbs_smsset), true)]

#endregion

namespace mysql_connection_test
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mobilespyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mobilespyEntities object using the connection string found in the 'mobilespyEntities' section of the application configuration file.
        /// </summary>
        public mobilespyEntities() : base("name=mobilespyEntities", "mobilespyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mobilespyEntities object.
        /// </summary>
        public mobilespyEntities(string connectionString) : base(connectionString, "mobilespyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mobilespyEntities object.
        /// </summary>
        public mobilespyEntities(EntityConnection connection) : base(connection, "mobilespyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mbs_callset> mbs_callset
        {
            get
            {
                if ((_mbs_callset == null))
                {
                    _mbs_callset = base.CreateObjectSet<mbs_callset>("mbs_callset");
                }
                return _mbs_callset;
            }
        }
        private ObjectSet<mbs_callset> _mbs_callset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mbs_contactpropertyset> mbs_contactpropertyset
        {
            get
            {
                if ((_mbs_contactpropertyset == null))
                {
                    _mbs_contactpropertyset = base.CreateObjectSet<mbs_contactpropertyset>("mbs_contactpropertyset");
                }
                return _mbs_contactpropertyset;
            }
        }
        private ObjectSet<mbs_contactpropertyset> _mbs_contactpropertyset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mbs_contactset> mbs_contactset
        {
            get
            {
                if ((_mbs_contactset == null))
                {
                    _mbs_contactset = base.CreateObjectSet<mbs_contactset>("mbs_contactset");
                }
                return _mbs_contactset;
            }
        }
        private ObjectSet<mbs_contactset> _mbs_contactset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mbs_deviceset> mbs_deviceset
        {
            get
            {
                if ((_mbs_deviceset == null))
                {
                    _mbs_deviceset = base.CreateObjectSet<mbs_deviceset>("mbs_deviceset");
                }
                return _mbs_deviceset;
            }
        }
        private ObjectSet<mbs_deviceset> _mbs_deviceset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mbs_filesystemset> mbs_filesystemset
        {
            get
            {
                if ((_mbs_filesystemset == null))
                {
                    _mbs_filesystemset = base.CreateObjectSet<mbs_filesystemset>("mbs_filesystemset");
                }
                return _mbs_filesystemset;
            }
        }
        private ObjectSet<mbs_filesystemset> _mbs_filesystemset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mbs_sessionset> mbs_sessionset
        {
            get
            {
                if ((_mbs_sessionset == null))
                {
                    _mbs_sessionset = base.CreateObjectSet<mbs_sessionset>("mbs_sessionset");
                }
                return _mbs_sessionset;
            }
        }
        private ObjectSet<mbs_sessionset> _mbs_sessionset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mbs_smsset> mbs_smsset
        {
            get
            {
                if ((_mbs_smsset == null))
                {
                    _mbs_smsset = base.CreateObjectSet<mbs_smsset>("mbs_smsset");
                }
                return _mbs_smsset;
            }
        }
        private ObjectSet<mbs_smsset> _mbs_smsset;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mbs_callset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTombs_callset(mbs_callset mbs_callset)
        {
            base.AddObject("mbs_callset", mbs_callset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mbs_contactpropertyset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTombs_contactpropertyset(mbs_contactpropertyset mbs_contactpropertyset)
        {
            base.AddObject("mbs_contactpropertyset", mbs_contactpropertyset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mbs_contactset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTombs_contactset(mbs_contactset mbs_contactset)
        {
            base.AddObject("mbs_contactset", mbs_contactset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mbs_deviceset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTombs_deviceset(mbs_deviceset mbs_deviceset)
        {
            base.AddObject("mbs_deviceset", mbs_deviceset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mbs_filesystemset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTombs_filesystemset(mbs_filesystemset mbs_filesystemset)
        {
            base.AddObject("mbs_filesystemset", mbs_filesystemset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mbs_sessionset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTombs_sessionset(mbs_sessionset mbs_sessionset)
        {
            base.AddObject("mbs_sessionset", mbs_sessionset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mbs_smsset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTombs_smsset(mbs_smsset mbs_smsset)
        {
            base.AddObject("mbs_smsset", mbs_smsset);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mobilespyModel", Name="mbs_callset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mbs_callset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mbs_callset object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="duration">Initial value of the Duration property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="startTimeStamp">Initial value of the StartTimeStamp property.</param>
        /// <param name="stopTimeStamp">Initial value of the StopTimeStamp property.</param>
        /// <param name="mBS_SessionId">Initial value of the MBS_SessionId property.</param>
        /// <param name="class">Initial value of the Class property.</param>
        public static mbs_callset Creatembs_callset(global::System.Int64 id, global::System.String number, global::System.Int32 duration, global::System.Int32 status, global::System.DateTime startTimeStamp, global::System.DateTime stopTimeStamp, global::System.Int64 mBS_SessionId, global::System.Int32 @class)
        {
            mbs_callset mbs_callset = new mbs_callset();
            mbs_callset.Id = id;
            mbs_callset.Number = number;
            mbs_callset.Duration = duration;
            mbs_callset.Status = status;
            mbs_callset.StartTimeStamp = startTimeStamp;
            mbs_callset.StopTimeStamp = stopTimeStamp;
            mbs_callset.MBS_SessionId = mBS_SessionId;
            mbs_callset.Class = @class;
            return mbs_callset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.Int32 _Duration;
        partial void OnDurationChanging(global::System.Int32 value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTimeStamp
        {
            get
            {
                return _StartTimeStamp;
            }
            set
            {
                OnStartTimeStampChanging(value);
                ReportPropertyChanging("StartTimeStamp");
                _StartTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTimeStamp");
                OnStartTimeStampChanged();
            }
        }
        private global::System.DateTime _StartTimeStamp;
        partial void OnStartTimeStampChanging(global::System.DateTime value);
        partial void OnStartTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StopTimeStamp
        {
            get
            {
                return _StopTimeStamp;
            }
            set
            {
                OnStopTimeStampChanging(value);
                ReportPropertyChanging("StopTimeStamp");
                _StopTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StopTimeStamp");
                OnStopTimeStampChanged();
            }
        }
        private global::System.DateTime _StopTimeStamp;
        partial void OnStopTimeStampChanging(global::System.DateTime value);
        partial void OnStopTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MBS_SessionId
        {
            get
            {
                return _MBS_SessionId;
            }
            set
            {
                OnMBS_SessionIdChanging(value);
                ReportPropertyChanging("MBS_SessionId");
                _MBS_SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MBS_SessionId");
                OnMBS_SessionIdChanged();
            }
        }
        private global::System.Int64 _MBS_SessionId;
        partial void OnMBS_SessionIdChanging(global::System.Int64 value);
        partial void OnMBS_SessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.Int32 _Class;
        partial void OnClassChanging(global::System.Int32 value);
        partial void OnClassChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_Call", "mbs_sessionset")]
        public mbs_sessionset mbs_sessionset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Call", "mbs_sessionset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Call", "mbs_sessionset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mbs_sessionset> mbs_sessionsetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Call", "mbs_sessionset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Call", "mbs_sessionset", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mobilespyModel", Name="mbs_contactpropertyset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mbs_contactpropertyset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mbs_contactpropertyset object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="property">Initial value of the Property property.</param>
        /// <param name="mBS_ContactId">Initial value of the MBS_ContactId property.</param>
        public static mbs_contactpropertyset Creatembs_contactpropertyset(global::System.Int64 id, global::System.Int32 property, global::System.Int64 mBS_ContactId)
        {
            mbs_contactpropertyset mbs_contactpropertyset = new mbs_contactpropertyset();
            mbs_contactpropertyset.Id = id;
            mbs_contactpropertyset.Property = property;
            mbs_contactpropertyset.MBS_ContactId = mBS_ContactId;
            return mbs_contactpropertyset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Property
        {
            get
            {
                return _Property;
            }
            set
            {
                OnPropertyChanging(value);
                ReportPropertyChanging("Property");
                _Property = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property");
                OnPropertyChanged();
            }
        }
        private global::System.Int32 _Property;
        partial void OnPropertyChanging(global::System.Int32 value);
        partial void OnPropertyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Datetime
        {
            get
            {
                return _Datetime;
            }
            set
            {
                OnDatetimeChanging(value);
                ReportPropertyChanging("Datetime");
                _Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Datetime");
                OnDatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Datetime;
        partial void OnDatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Binary
        {
            get
            {
                return StructuralObject.GetValidValue(_Binary);
            }
            set
            {
                OnBinaryChanging(value);
                ReportPropertyChanging("Binary");
                _Binary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Binary");
                OnBinaryChanged();
            }
        }
        private global::System.Byte[] _Binary;
        partial void OnBinaryChanging(global::System.Byte[] value);
        partial void OnBinaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MBS_ContactId
        {
            get
            {
                return _MBS_ContactId;
            }
            set
            {
                OnMBS_ContactIdChanging(value);
                ReportPropertyChanging("MBS_ContactId");
                _MBS_ContactId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MBS_ContactId");
                OnMBS_ContactIdChanged();
            }
        }
        private global::System.Int64 _MBS_ContactId;
        partial void OnMBS_ContactIdChanging(global::System.Int64 value);
        partial void OnMBS_ContactIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_ContactMBS_ContactProperty", "mbs_contactset")]
        public mbs_contactset mbs_contactset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_contactset>("mobilespyModel.FK_MBS_ContactMBS_ContactProperty", "mbs_contactset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_contactset>("mobilespyModel.FK_MBS_ContactMBS_ContactProperty", "mbs_contactset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mbs_contactset> mbs_contactsetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_contactset>("mobilespyModel.FK_MBS_ContactMBS_ContactProperty", "mbs_contactset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mbs_contactset>("mobilespyModel.FK_MBS_ContactMBS_ContactProperty", "mbs_contactset", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mobilespyModel", Name="mbs_contactset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mbs_contactset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mbs_contactset object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="mBS_SessionId">Initial value of the MBS_SessionId property.</param>
        /// <param name="class">Initial value of the Class property.</param>
        public static mbs_contactset Creatembs_contactset(global::System.Int64 id, global::System.Int64 mBS_SessionId, global::System.Int32 @class)
        {
            mbs_contactset mbs_contactset = new mbs_contactset();
            mbs_contactset.Id = id;
            mbs_contactset.MBS_SessionId = mBS_SessionId;
            mbs_contactset.Class = @class;
            return mbs_contactset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MBS_SessionId
        {
            get
            {
                return _MBS_SessionId;
            }
            set
            {
                OnMBS_SessionIdChanging(value);
                ReportPropertyChanging("MBS_SessionId");
                _MBS_SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MBS_SessionId");
                OnMBS_SessionIdChanged();
            }
        }
        private global::System.Int64 _MBS_SessionId;
        partial void OnMBS_SessionIdChanging(global::System.Int64 value);
        partial void OnMBS_SessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.Int32 _Class;
        partial void OnClassChanging(global::System.Int32 value);
        partial void OnClassChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_ContactMBS_ContactProperty", "mbs_contactpropertyset")]
        public EntityCollection<mbs_contactpropertyset> mbs_contactpropertyset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mbs_contactpropertyset>("mobilespyModel.FK_MBS_ContactMBS_ContactProperty", "mbs_contactpropertyset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mbs_contactpropertyset>("mobilespyModel.FK_MBS_ContactMBS_ContactProperty", "mbs_contactpropertyset", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_Contact", "mbs_sessionset")]
        public mbs_sessionset mbs_sessionset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Contact", "mbs_sessionset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Contact", "mbs_sessionset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mbs_sessionset> mbs_sessionsetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Contact", "mbs_sessionset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Contact", "mbs_sessionset", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mobilespyModel", Name="mbs_deviceset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mbs_deviceset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mbs_deviceset object.
        /// </summary>
        /// <param name="uID">Initial value of the UID property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static mbs_deviceset Creatembs_deviceset(global::System.String uID, global::System.String type)
        {
            mbs_deviceset mbs_deviceset = new mbs_deviceset();
            mbs_deviceset.UID = uID;
            mbs_deviceset.Type = type;
            return mbs_deviceset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UID
        {
            get
            {
                return _UID;
            }
            set
            {
                if (_UID != value)
                {
                    OnUIDChanging(value);
                    ReportPropertyChanging("UID");
                    _UID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UID");
                    OnUIDChanged();
                }
            }
        }
        private global::System.String _UID;
        partial void OnUIDChanging(global::System.String value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ESN
        {
            get
            {
                return _ESN;
            }
            set
            {
                OnESNChanging(value);
                ReportPropertyChanging("ESN");
                _ESN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ESN");
                OnESNChanged();
            }
        }
        private global::System.String _ESN;
        partial void OnESNChanging(global::System.String value);
        partial void OnESNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Lac
        {
            get
            {
                return _Lac;
            }
            set
            {
                OnLacChanging(value);
                ReportPropertyChanging("Lac");
                _Lac = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lac");
                OnLacChanged();
            }
        }
        private Nullable<global::System.Int64> _Lac;
        partial void OnLacChanging(Nullable<global::System.Int64> value);
        partial void OnLacChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Cid
        {
            get
            {
                return _Cid;
            }
            set
            {
                OnCidChanging(value);
                ReportPropertyChanging("Cid");
                _Cid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cid");
                OnCidChanged();
            }
        }
        private Nullable<global::System.Int64> _Cid;
        partial void OnCidChanging(Nullable<global::System.Int64> value);
        partial void OnCidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HWRevision
        {
            get
            {
                return _HWRevision;
            }
            set
            {
                OnHWRevisionChanging(value);
                ReportPropertyChanging("HWRevision");
                _HWRevision = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HWRevision");
                OnHWRevisionChanged();
            }
        }
        private global::System.String _HWRevision;
        partial void OnHWRevisionChanging(global::System.String value);
        partial void OnHWRevisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMEI
        {
            get
            {
                return _IMEI;
            }
            set
            {
                OnIMEIChanging(value);
                ReportPropertyChanging("IMEI");
                _IMEI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMEI");
                OnIMEIChanged();
            }
        }
        private global::System.String _IMEI;
        partial void OnIMEIChanging(global::System.String value);
        partial void OnIMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private Nullable<global::System.Int64> _Phone;
        partial void OnPhoneChanging(Nullable<global::System.Int64> value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Platform
        {
            get
            {
                return _Platform;
            }
            set
            {
                OnPlatformChanging(value);
                ReportPropertyChanging("Platform");
                _Platform = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Platform");
                OnPlatformChanged();
            }
        }
        private global::System.String _Platform;
        partial void OnPlatformChanging(global::System.String value);
        partial void OnPlatformChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnedIMEI
        {
            get
            {
                return _ReturnedIMEI;
            }
            set
            {
                OnReturnedIMEIChanging(value);
                ReportPropertyChanging("ReturnedIMEI");
                _ReturnedIMEI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnedIMEI");
                OnReturnedIMEIChanged();
            }
        }
        private global::System.String _ReturnedIMEI;
        partial void OnReturnedIMEIChanging(global::System.String value);
        partial void OnReturnedIMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SWRevision
        {
            get
            {
                return _SWRevision;
            }
            set
            {
                OnSWRevisionChanging(value);
                ReportPropertyChanging("SWRevision");
                _SWRevision = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SWRevision");
                OnSWRevisionChanged();
            }
        }
        private global::System.String _SWRevision;
        partial void OnSWRevisionChanging(global::System.String value);
        partial void OnSWRevisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMSI
        {
            get
            {
                return _IMSI;
            }
            set
            {
                OnIMSIChanging(value);
                ReportPropertyChanging("IMSI");
                _IMSI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMSI");
                OnIMSIChanged();
            }
        }
        private global::System.String _IMSI;
        partial void OnIMSIChanging(global::System.String value);
        partial void OnIMSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ICCID
        {
            get
            {
                return _ICCID;
            }
            set
            {
                OnICCIDChanging(value);
                ReportPropertyChanging("ICCID");
                _ICCID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ICCID");
                OnICCIDChanged();
            }
        }
        private global::System.String _ICCID;
        partial void OnICCIDChanging(global::System.String value);
        partial void OnICCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LAI
        {
            get
            {
                return _LAI;
            }
            set
            {
                OnLAIChanging(value);
                ReportPropertyChanging("LAI");
                _LAI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LAI");
                OnLAIChanged();
            }
        }
        private global::System.String _LAI;
        partial void OnLAIChanging(global::System.String value);
        partial void OnLAIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phrase
        {
            get
            {
                return _Phrase;
            }
            set
            {
                OnPhraseChanging(value);
                ReportPropertyChanging("Phrase");
                _Phrase = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phrase");
                OnPhraseChanged();
            }
        }
        private global::System.String _Phrase;
        partial void OnPhraseChanging(global::System.String value);
        partial void OnPhraseChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_DeviceMBS_Session", "mbs_sessionset")]
        public EntityCollection<mbs_sessionset> mbs_sessionset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mbs_sessionset>("mobilespyModel.FK_MBS_DeviceMBS_Session", "mbs_sessionset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mbs_sessionset>("mobilespyModel.FK_MBS_DeviceMBS_Session", "mbs_sessionset", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mobilespyModel", Name="mbs_filesystemset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mbs_filesystemset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mbs_filesystemset object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="mappingRootPath">Initial value of the MappingRootPath property.</param>
        /// <param name="mBS_SessionId">Initial value of the MBS_SessionId property.</param>
        public static mbs_filesystemset Creatembs_filesystemset(global::System.Int64 id, global::System.String mappingRootPath, global::System.Int64 mBS_SessionId)
        {
            mbs_filesystemset mbs_filesystemset = new mbs_filesystemset();
            mbs_filesystemset.Id = id;
            mbs_filesystemset.MappingRootPath = mappingRootPath;
            mbs_filesystemset.MBS_SessionId = mBS_SessionId;
            return mbs_filesystemset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MappingRootPath
        {
            get
            {
                return _MappingRootPath;
            }
            set
            {
                OnMappingRootPathChanging(value);
                ReportPropertyChanging("MappingRootPath");
                _MappingRootPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MappingRootPath");
                OnMappingRootPathChanged();
            }
        }
        private global::System.String _MappingRootPath;
        partial void OnMappingRootPathChanging(global::System.String value);
        partial void OnMappingRootPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MBS_SessionId
        {
            get
            {
                return _MBS_SessionId;
            }
            set
            {
                OnMBS_SessionIdChanging(value);
                ReportPropertyChanging("MBS_SessionId");
                _MBS_SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MBS_SessionId");
                OnMBS_SessionIdChanged();
            }
        }
        private global::System.Int64 _MBS_SessionId;
        partial void OnMBS_SessionIdChanging(global::System.Int64 value);
        partial void OnMBS_SessionIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_FileSystem", "mbs_sessionset")]
        public mbs_sessionset mbs_sessionset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_FileSystem", "mbs_sessionset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_FileSystem", "mbs_sessionset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mbs_sessionset> mbs_sessionsetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_FileSystem", "mbs_sessionset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_FileSystem", "mbs_sessionset", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mobilespyModel", Name="mbs_sessionset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mbs_sessionset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mbs_sessionset object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="mBS_DeviceUID">Initial value of the MBS_DeviceUID property.</param>
        public static mbs_sessionset Creatembs_sessionset(global::System.Int64 id, global::System.DateTime timestamp, global::System.String mBS_DeviceUID)
        {
            mbs_sessionset mbs_sessionset = new mbs_sessionset();
            mbs_sessionset.Id = id;
            mbs_sessionset.Timestamp = timestamp;
            mbs_sessionset.MBS_DeviceUID = mBS_DeviceUID;
            return mbs_sessionset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MBS_DeviceUID
        {
            get
            {
                return _MBS_DeviceUID;
            }
            set
            {
                OnMBS_DeviceUIDChanging(value);
                ReportPropertyChanging("MBS_DeviceUID");
                _MBS_DeviceUID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MBS_DeviceUID");
                OnMBS_DeviceUIDChanged();
            }
        }
        private global::System.String _MBS_DeviceUID;
        partial void OnMBS_DeviceUIDChanging(global::System.String value);
        partial void OnMBS_DeviceUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentSessionId
        {
            get
            {
                return _ParentSessionId;
            }
            set
            {
                OnParentSessionIdChanging(value);
                ReportPropertyChanging("ParentSessionId");
                _ParentSessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentSessionId");
                OnParentSessionIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentSessionId;
        partial void OnParentSessionIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentSessionIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_Call", "mbs_callset")]
        public EntityCollection<mbs_callset> mbs_callset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mbs_callset>("mobilespyModel.FK_MBS_SessionMBS_Call", "mbs_callset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mbs_callset>("mobilespyModel.FK_MBS_SessionMBS_Call", "mbs_callset", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_Contact", "mbs_contactset")]
        public EntityCollection<mbs_contactset> mbs_contactset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mbs_contactset>("mobilespyModel.FK_MBS_SessionMBS_Contact", "mbs_contactset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mbs_contactset>("mobilespyModel.FK_MBS_SessionMBS_Contact", "mbs_contactset", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_DeviceMBS_Session", "mbs_deviceset")]
        public mbs_deviceset mbs_deviceset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_deviceset>("mobilespyModel.FK_MBS_DeviceMBS_Session", "mbs_deviceset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_deviceset>("mobilespyModel.FK_MBS_DeviceMBS_Session", "mbs_deviceset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mbs_deviceset> mbs_devicesetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_deviceset>("mobilespyModel.FK_MBS_DeviceMBS_Session", "mbs_deviceset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mbs_deviceset>("mobilespyModel.FK_MBS_DeviceMBS_Session", "mbs_deviceset", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_FileSystem", "mbs_filesystemset")]
        public EntityCollection<mbs_filesystemset> mbs_filesystemset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mbs_filesystemset>("mobilespyModel.FK_MBS_SessionMBS_FileSystem", "mbs_filesystemset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mbs_filesystemset>("mobilespyModel.FK_MBS_SessionMBS_FileSystem", "mbs_filesystemset", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_Session", "mbs_sessionset1")]
        public EntityCollection<mbs_sessionset> mbs_sessionset1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Session", "mbs_sessionset1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Session", "mbs_sessionset1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_Session", "mbs_sessionset")]
        public mbs_sessionset mbs_sessionset2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Session", "mbs_sessionset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Session", "mbs_sessionset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mbs_sessionset> mbs_sessionset2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Session", "mbs_sessionset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_Session", "mbs_sessionset", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_SMS", "mbs_smsset")]
        public EntityCollection<mbs_smsset> mbs_smsset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mbs_smsset>("mobilespyModel.FK_MBS_SessionMBS_SMS", "mbs_smsset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mbs_smsset>("mobilespyModel.FK_MBS_SessionMBS_SMS", "mbs_smsset", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mobilespyModel", Name="mbs_smsset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mbs_smsset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mbs_smsset object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="mBS_SessionId">Initial value of the MBS_SessionId property.</param>
        /// <param name="class">Initial value of the Class property.</param>
        public static mbs_smsset Creatembs_smsset(global::System.Int64 id, global::System.Int64 mBS_SessionId, global::System.Int32 @class)
        {
            mbs_smsset mbs_smsset = new mbs_smsset();
            mbs_smsset.Id = id;
            mbs_smsset.MBS_SessionId = mBS_SessionId;
            mbs_smsset.Class = @class;
            return mbs_smsset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromNumber
        {
            get
            {
                return _FromNumber;
            }
            set
            {
                OnFromNumberChanging(value);
                ReportPropertyChanging("FromNumber");
                _FromNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromNumber");
                OnFromNumberChanged();
            }
        }
        private global::System.String _FromNumber;
        partial void OnFromNumberChanging(global::System.String value);
        partial void OnFromNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReceivedTimeStamp
        {
            get
            {
                return _ReceivedTimeStamp;
            }
            set
            {
                OnReceivedTimeStampChanging(value);
                ReportPropertyChanging("ReceivedTimeStamp");
                _ReceivedTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReceivedTimeStamp");
                OnReceivedTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReceivedTimeStamp;
        partial void OnReceivedTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnReceivedTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SentTimeStamp
        {
            get
            {
                return _SentTimeStamp;
            }
            set
            {
                OnSentTimeStampChanging(value);
                ReportPropertyChanging("SentTimeStamp");
                _SentTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SentTimeStamp");
                OnSentTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _SentTimeStamp;
        partial void OnSentTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnSentTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Head
        {
            get
            {
                return _Head;
            }
            set
            {
                OnHeadChanging(value);
                ReportPropertyChanging("Head");
                _Head = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Head");
                OnHeadChanged();
            }
        }
        private global::System.String _Head;
        partial void OnHeadChanging(global::System.String value);
        partial void OnHeadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ReceivedTimeZone
        {
            get
            {
                return _ReceivedTimeZone;
            }
            set
            {
                OnReceivedTimeZoneChanging(value);
                ReportPropertyChanging("ReceivedTimeZone");
                _ReceivedTimeZone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReceivedTimeZone");
                OnReceivedTimeZoneChanged();
            }
        }
        private Nullable<global::System.Int64> _ReceivedTimeZone;
        partial void OnReceivedTimeZoneChanging(Nullable<global::System.Int64> value);
        partial void OnReceivedTimeZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceCenter
        {
            get
            {
                return _ServiceCenter;
            }
            set
            {
                OnServiceCenterChanging(value);
                ReportPropertyChanging("ServiceCenter");
                _ServiceCenter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceCenter");
                OnServiceCenterChanged();
            }
        }
        private global::System.String _ServiceCenter;
        partial void OnServiceCenterChanging(global::System.String value);
        partial void OnServiceCenterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int16> _State;
        partial void OnStateChanging(Nullable<global::System.Int16> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.SByte> _Status;
        partial void OnStatusChanging(Nullable<global::System.SByte> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ToNumber
        {
            get
            {
                return _ToNumber;
            }
            set
            {
                OnToNumberChanging(value);
                ReportPropertyChanging("ToNumber");
                _ToNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ToNumber");
                OnToNumberChanged();
            }
        }
        private global::System.String _ToNumber;
        partial void OnToNumberChanging(global::System.String value);
        partial void OnToNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int16> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int16> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MBS_SessionId
        {
            get
            {
                return _MBS_SessionId;
            }
            set
            {
                OnMBS_SessionIdChanging(value);
                ReportPropertyChanging("MBS_SessionId");
                _MBS_SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MBS_SessionId");
                OnMBS_SessionIdChanged();
            }
        }
        private global::System.Int64 _MBS_SessionId;
        partial void OnMBS_SessionIdChanging(global::System.Int64 value);
        partial void OnMBS_SessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.Int32 _Class;
        partial void OnClassChanging(global::System.Int32 value);
        partial void OnClassChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mobilespyModel", "FK_MBS_SessionMBS_SMS", "mbs_sessionset")]
        public mbs_sessionset mbs_sessionset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_SMS", "mbs_sessionset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_SMS", "mbs_sessionset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mbs_sessionset> mbs_sessionsetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_SMS", "mbs_sessionset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mbs_sessionset>("mobilespyModel.FK_MBS_SessionMBS_SMS", "mbs_sessionset", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
