//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbs_sessionset
    {
        public mbs_sessionset()
        {
            this.mbs_callset = new HashSet<mbs_callset>();
            this.mbs_contactset = new HashSet<mbs_contactset>();
            this.mbs_filesystemset = new HashSet<mbs_filesystemset>();
            this.mbs_sessionset1 = new HashSet<mbs_sessionset>();
            this.mbs_smsset = new HashSet<mbs_smsset>();
        }
    
        public long Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string MBS_DeviceUID { get; set; }
        public Nullable<long> ParentSessionId { get; set; }
    
        public virtual ICollection<mbs_callset> mbs_callset { get; set; }
        public virtual ICollection<mbs_contactset> mbs_contactset { get; set; }
        public virtual mbs_deviceset mbs_deviceset { get; set; }
        public virtual ICollection<mbs_filesystemset> mbs_filesystemset { get; set; }
        public virtual ICollection<mbs_sessionset> mbs_sessionset1 { get; set; }
        public virtual mbs_sessionset mbs_sessionset2 { get; set; }
        public virtual ICollection<mbs_smsset> mbs_smsset { get; set; }
    }
}
