//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbs_contactset
    {
        public mbs_contactset()
        {
            this.mbs_contactpropertyset = new HashSet<mbs_contactpropertyset>();
        }
    
        public long Id { get; set; }
        public string Label { get; set; }
        public long MBS_SessionId { get; set; }
        public int Class { get; set; }
    
        public virtual ICollection<mbs_contactpropertyset> mbs_contactpropertyset { get; set; }
        public virtual mbs_sessionset mbs_sessionset { get; set; }
    }
}
