//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbs_deviceset
    {
        public mbs_deviceset()
        {
            this.mbs_sessionset = new HashSet<mbs_sessionset>();
        }
    
        public string UID { get; set; }
        public string Type { get; set; }
        public string Label { get; set; }
        public string Manufacturer { get; set; }
        public string Product { get; set; }
        public string ESN { get; set; }
        public Nullable<long> Lac { get; set; }
        public Nullable<long> Cid { get; set; }
        public string HWRevision { get; set; }
        public string IMEI { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Platform { get; set; }
        public string ReturnedIMEI { get; set; }
        public string SWRevision { get; set; }
        public string IMSI { get; set; }
        public string ICCID { get; set; }
        public string LAI { get; set; }
        public string Phrase { get; set; }
    
        public virtual ICollection<mbs_sessionset> mbs_sessionset { get; set; }
    }
}
